on:
  push:
    branches: [ staging, trying, master ]
  pull_request:

name: Continuous integration

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mcu:
          - stm32f100
          - stm32f101
          - stm32f103
          - stm32f105
          - stm32f107
        rust:
          - stable
        include:
          - rust: nightly
            mcu: stm32f103
            experimental: true

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          target: thumbv7m-none-eabi
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: check
          args: --features=${{ matrix.mcu }},rt --examples
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --features=${{ matrix.mcu }} --target x86_64-unknown-linux-gnu --lib
